// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Assigment5YoutubecomTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void assigment5Youtubecom() {
    // Test name: Assigment_5_Youtube.com
    // Step # | name | target | value | comment
    // 1 | open | https://www.youtube.com/ |  | 
    driver.get("https://www.youtube.com/");
    // 2 | setWindowSize | 1296x1400 |  | 
    driver.manage().window().setSize(new Dimension(1296, 1400));
    // 3 | click | name=search_query |  | 
    driver.findElement(By.name("search_query")).click();
    // 4 | type | name=search_query | kage | 
    driver.findElement(By.name("search_query")).sendKeys("kage");
    // 5 | sendKeys | name=search_query | ${KEY_ENTER} | 
    driver.findElement(By.name("search_query")).sendKeys(Keys.ENTER);
    // 6 | mouseOver | css=.ytd-item-section-renderer:nth-child(1) > #dismissable #thumbnail #img |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-item-section-renderer:nth-child(1) > #dismissable #thumbnail #img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | css=.ytd-item-section-renderer:nth-child(1) > #dismissable #thumbnail #img |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | mouseOver | css=.ytd-item-section-renderer:nth-child(2) > #dismissable #thumbnail #img |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-item-section-renderer:nth-child(2) > #dismissable #thumbnail #img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | mouseOut | css=.ytd-item-section-renderer:nth-child(2) > #dismissable #thumbnail #img |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | mouseOver | css=.style-scope:nth-child(5) > #dismissable #thumbnail #img |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(5) > #dismissable #thumbnail #img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | mouseOut | css=.style-scope:nth-child(5) > #dismissable #thumbnail #img |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 12 | click | css=.style-scope:nth-child(5) > #dismissable #play |  | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(5) > #dismissable #play")).click();
    // 13 | mouseOver | css=.style-scope:nth-child(3) > #dismissable > .details #byline-container |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(3) > #dismissable > .details #byline-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseOut | css=.style-scope:nth-child(3) > #dismissable > .details #byline-container |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 15 | mouseOver | css=.style-scope:nth-child(4) > #dismissable > .details #metadata-line |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(4) > #dismissable > .details #metadata-line"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 16 | mouseOut | css=.style-scope:nth-child(4) > #dismissable > .details #metadata-line |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 17 | click | css=.video-stream |  | 
    driver.findElement(By.cssSelector(".video-stream")).click();
    // 18 | click | css=#meta-contents > .style-scope > #container |  | 
    driver.findElement(By.cssSelector("#meta-contents > .style-scope > #container")).click();
  }
}
