// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Assigment5FillOutFormTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void assigment5FillOutForm() {
    // Test name: Assigment_5_FillOutForm
    // Step # | name | target | value | comment
    // 1 | open | https://sqengineer.com/practice-sites/basic-web-elements/ |  | 
    driver.get("https://sqengineer.com/practice-sites/basic-web-elements/");
    // 2 | setWindowSize | 1296x1400 |  | 
    driver.manage().window().setSize(new Dimension(1296, 1400));
    // 3 | click | id=firstName |  | 
    driver.findElement(By.id("firstName")).click();
    // 4 | type | id=firstName | tester | 
    driver.findElement(By.id("firstName")).sendKeys("tester");
    // 5 | click | id=lastName |  | 
    driver.findElement(By.id("lastName")).click();
    // 6 | type | id=lastName | selenium | 
    driver.findElement(By.id("lastName")).sendKeys("selenium");
    // 7 | click | id=maleGender |  | 
    driver.findElement(By.id("maleGender")).click();
    // 8 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 9 | type | id=email | ide@nu.com | 
    driver.findElement(By.id("email")).sendKeys("ide@nu.com");
    // 10 | click | id=selectBox |  | 
    driver.findElement(By.id("selectBox")).click();
    // 11 | select | id=selectBox | label=Los Angeles | 
    {
      WebElement dropdown = driver.findElement(By.id("selectBox"));
      dropdown.findElement(By.xpath("//option[. = 'Los Angeles']")).click();
    }
    // 12 | click | id=selectBox |  | 
    driver.findElement(By.id("selectBox")).click();
    // 13 | click | css=input:nth-child(27) |  | 
    driver.findElement(By.cssSelector("input:nth-child(27)")).click();
  }
}
